name: API CI Pipeline

on:
  push:
    branches: ["master"]
    paths:
      - "api/**"
  pull_request:
    branches: ["master"]
    paths:
      - "api/**"

env:
  DOTNET_VERSION: "8.0.x"
  API_PROJECT_PATH: "api/api.csproj"
  TEST_PROJECT_PATH: "testing/api-tests/api-tests.csproj"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ${{ env.API_PROJECT_PATH }} # Restore project dependencies for API project

      - name: Clean
        run: dotnet clean ${{ env.API_PROJECT_PATH }} --configuration Release # Clean the API project

      - name: Build app
        run: dotnet build ${{ env.API_PROJECT_PATH }} -c Release --no-restore # Build the API project

      - name: Restore Test dependencies
        run: dotnet restore ${{ env.TEST_PROJECT_PATH }} # Restore project dependencies for testing project

      - name: Clean Test
        run: dotnet clean ${{ env.TEST_PROJECT_PATH }} --configuration Release # Clean the testing project

      - name: Build Test
        run: dotnet build ${{ env.TEST_PROJECT_PATH }} -c Release --no-restore # Build the testing project

      - name: Test
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} --no-build --verbosity normal
