name: API CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '8.0.x'
  API_PROJECT_PATH: 'api/api.csproj' # Adjust this to the path of your .NET API project or solution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ${{ env.API_PROJECT_PATH }} # Restore project dependencies for your API project

      - name: Clean
        run: dotnet clean ${{ env.API_PROJECT_PATH }} --configuration Release # Clean the API project

      - name: Build app
        run: dotnet build ${{ env.API_PROJECT_PATH }} -c Release --no-restore # Build the API project
