name: React CD for Prodution

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend/**'

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - name: Deploy to Firebase Hosting
        id: firebase_hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BARBERSHOUSEPROJECT_419414 }}
          channelId: live
          projectId: barbershouseproject-419414
          entryPoint:  "./frontend"
